defaultSemverRangePrefix: ''

packageExtensions:
  '@octokit/plugin-retry@4.1.6':
    dependencies:
      '@octokit/request-error': 3.0.3

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@ojkelly/plugin-all.cjs
    spec: 'https://yarn.build/latest'

yarnPath: .yarn/releases/yarn-3.6.4.cjs
