name: Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    strategy:
      matrix:
        node-version: [18, 20, 21]
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Meta
        id: meta
        run: echo "node-version=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      - name: Use Node.js ${{ matrix.node-version }}
        id: node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restore cache
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            .yarn/unplugged
            .yarn/install-state.gz
          key: ${{ runner.os }}-yarn-${{ steps.node.outputs.node-version }}-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
