name: Pull Request

on:
  pull_request:
    types: [opened, synchronize]

  workflow_call:
    inputs:
      build:
        description: Should it test by building?
        required: false
        default: true
        type: boolean

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Meta
        id: meta
        run: echo "node-version=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restore cache
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            .yarn/unplugged
            .yarn/install-state.gz
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --immutable

      - name: Build
        if: ${{ inputs.build }}
        run: yarn build

      - name: Test
        run: yarn test

      - name: Report Test Coverage
        if: github.base_ref != '' && startsWith(matrix.node-version, steps.meta.outputs.node-version)
        uses: vebr/jest-lcov-reporter@v0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
