name: Publish

on:
  push:
    branches: [main]

jobs:
  publish-test:
    uses: ./.github/workflows/pull-request.yml
    with:
      build: false

  publish-npm:
    name: NPM
    environment: npm
    needs: [publish-test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: read

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Restore cache
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            .yarn/unplugged
            .yarn/install-state.gz
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
